// This Source Code Form is subject to the terms of the Mozilla Public
// License, v2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/

export type RegisteredIconNames =
  | "Add"
  | "AddCircle"
  | "AddIn"
  | "BacklogList"
  | "Blockhead"
  | "BlockheadFilled"
  | "BookStar"
  | "Cancel"
  | "DatabaseSettings"
  | "Delete"
  | "Edit"
  | "ErrorBadge"
  | "FileASPX"
  | "FiveTileGrid"
  | "Flow"
  | "GenericScan"
  | "OpenFile"
  | "PanelSettings"
  | "RectangularClipping"
  | "Settings"
  | "Variable2"
  | "ROS"
  | "AddChart"
  | "Background"
  | "Camera"
  | "Cells"
  | "Check"
  | "Circle"
  | "Clear"
  | "Clock"
  | "Collapse"
  | "Cube"
  | "Expand"
  | "Flag"
  | "Folder"
  | "FolderOpen"
  | "Grid"
  | "Hive"
  | "ImageProjection"
  | "Map"
  | "Move"
  | "MoveDown"
  | "MoveUp"
  | "NorthWest"
  | "Note"
  | "NoteFilled"
  | "Points"
  | "PrecisionManufacturing"
  | "Radar"
  | "Shapes"
  | "Share"
  | "SouthEast"
  | "Star"
  | "Timeline"
  | "Topic"
  | "Walk"
  | "World"
  | never; // never has no effect here other than keeping the semicolon on a separate line for easier conflict resolution
